config/routes.rb
Rails.application.routes.draw do
  resources :types
  resources :members
  resources :posts
  resources :clubs
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  resources :users do
    resources :clubs, only: [:index, :show]
    resources :posts
  end

  root 'clubs#index'

  get 'posts/:id/post_data', to: 'posts#post_data'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, [Club, Post]

    if !user.nil?
      can :manage, Club, user: user
      can :manage, Comment, user: user
    end
  end
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :posts, dependent: :destroy #deletes posts if club is deleted
  belongs_to :user
  belongs_to :type
  has_many :members

  accepts_nested_attributes_for :members, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true

  validates :name, :presence => true
  validates :name, :uniqueness => true
  validates :description, :presence => true

  def member_attributes=(member_attribute)
    member << Member.find_or_create_by(member_attribute)
  end

  def self.popular?(pop)
    where("member_number >= ?", pop)
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :club

  def self.search(position)
    Member.all.select{|member| member.position == position}
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :club

  validates :content, :presence => true
  validates :title, :presence => true
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :clubs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :posts, dependent: :destroy #deletes posts if user is deleted
  has_many :clubs

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
      user = User.create(email: data["email"],
        password: Devise.friendly_token[0,20])
      end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html, :js, :json

  def index
    @clubs = Club.all
    respond_with(@clubs)
  end

  def show
    @club = Club.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @club }
    end
  end

  def new
    @club = Club.new
    3.times {@club.members.build}
    respond_with(@club)
  end

  def edit
    3.times {@club.members.build}
  end

  def create
    @club = Club.new(club_params)
    flash[:notice] = 'Club was successfully created.' if @club.save
    respond_with(@club)
  end

  def update
    flash[:notice] = 'Club successfully updated.' if @club.update(club_params)
    respond_with(@club)
  end

  def destroy
    @club.destroy
    respond_with(@club)
  end

  private
    def set_club
      @club = Club.find(params[:id])
    end

    def club_params
      params.require(:club).permit(
        :name, 
        :description,
        :member_number, 
        :type_id,
        :posts,
        members_attributes: [:id, :name, :position, :_destroy])
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def search
  end

  def show
    @members = Member.search(params[:position])
    @position = params[:position]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html, :js

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def create
    @post = Post.new(post_params)
    flash[:notice] = 'Post was successfully created.' if @post.save
    respond_with(@post)
  end

  def edit
  end

  def update
    flash[:notice] = 'Post successfully updated.' if @post.update(post_params)
    respond_with(@post)
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    flash[:notice] = 'Post successfully deleted.' if @post.destroy
    respond_with(@post)
  end

  def post_data
    post = Post.find(params[:id])
    render json: post.to_json(only: [:title, :content, :id])
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(
        :content,
        :title, 
        :club_id, 
        :user_id
      )
    end
end

# May remove flash[:notices] or find another way, because they only show on
# refresh somewhat defeats the purpose if you edit mulitiple posts. 

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @types = Type.all
    @type = Type.new
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @types }
    end
  end

  def new
    @type = Type.new
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @type}
        format.js {}
      end
    else
      render :index
    end
  end

  def show
    @type = Type.find_by(id: params[:id])
    respond_to do |format|
      format.html { render :show}
      format.json { render json: @type }
      format.js {}
    end
  end

  private
    def type_params
      params.require(:type).permit(:name)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
  def authorize_edit_and_destroy(object)
    link_to "edit", edit_club_path(object) if can? :update, object
    link_to "delete", club_path(object), method: "DELETE" if can? :destroy, object
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/clubs/_club.html.erb
<%= div_for club do %>
  <div class="panel">
    <p><strong>Name:</strong> <%= link_to club.name, club_path(club) %></p>
    <p><strong>Description:</strong> <%= club.description %></p>
    <p><strong>Number of Members:</strong> <%= club.member_number %></p>
    <p><strong>Club Type:</strong> <%= link_to club.type.name, type_path(club.type) %>
    </p>
    <h5><strong>Members:</strong></h5>
    <div class="show-members">
        <% if club.members.any? %>
        <% club.members.each do |member| %>
            <strong><%= member.position %></strong> - <%= member.name %><br>
        <% end %>
        <% else %>
            <p>No members</p>
        <% end %>
    </div>
    

    <%= link_to 'Edit Club', edit_club_path(club), remote: true %> |
    <%= link_to 'Delete Club', club, remote: true, method: :delete %>
    <hr><br>
  </div>
<% end %>

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :member_number %><br>
    <%= f.number_field :member_number %>
  </div><br>

  <div class="field">
    <%= f.label :type_id %>
    <%= f.collection_select :type_id, Type.all, :id, :name %>
  </div><br>
  
  <div class="field">
    <h5>Club Leaders:</h5>
    <%= f.fields_for :members do |m| %>
      <%= m.label :name %>
      <%= m.text_field :name %>
      <%= m.label :position %>
      <%= m.text_field :position %>
      <%= m.check_box :_destroy %>
      <%= m.label :_destroy, 'remove' %><br>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clubs/create.js.erb
$('.all-clubs').append('<%= j render partial: ('club'), locals: {club: @club} %>');
$('.new-club-button').show();
$('form').hide();

app/views/clubs/destroy.js.erb
$('div#<%= dom_id(@club) %>').fadeOut();

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/edit.js.erb
$('form').hide();
$('div#<%= dom_id(@club) %>').find('.panel').append('<%= j render("form") %>');

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="new-club-form">
  <button class="btn"><%= link_to 'Create a new club', new_club_path, remote: true, class: "new-club-button" %></button><br><br>
</div>
<hr>

<button class="btn"><%= link_to "Manage the types of clubs.", types_path %></button>
<hr>

<div class="all-clubs">
  <h1>Listing Clubs</h1>
  <% @clubs.each do |club| %>
    <%= render club %>
  <% end %>
</div>

<h3>My Posts:</h3>
<% if !current_user.posts.empty? %>
  <% current_user.posts.reverse_each do |post| %>
    <p>Club: <%= post.club.name %></p>
    <%= render partial: "posts/post", locals: {post: post} %>
  <% end %>
<% else %>
  <p>You don't have any posts yet.</p>
<% end %>

app/views/clubs/new.js.erb
$('.new-club-button').after('<%= j render ("form") %>');
$('.new-club-button').hide(); //hides new club button so you only have one open at a time.

app/views/clubs/popular.html.erb
<div>
  <h1>All of the clubs with <%= params[:position] %> or more members.</h1>
  <% @results.each do |member|%>
    <p><%= club.name %> with <%= club.member_number %></p>
  <% end %>
</div>

app/views/clubs/popular_clubs.html.erb
<%= form_tag(popular_clubs_path, method: "get", id: "popular-form") do %>
  <h3>How many members should a club have to be popular?</h3>
  <%= text_field_tag :popularity, params[:popularity] %>
  <%= submit_tag "Submit" %>
<% end %>

<% if @clubs.present? %>
  <h1>All of the clubs with <%= params[:popularity] %> or more members.</h1>
  <% @clubs.each do |club|%>
    <p><%= link_to club.name, club_path(club) %>
    with <%= club.member_number %> members.</p>
  <% end %>
<% else %>
  <p>There are no clubs that have <%= params[:popularity] %> or more members.</p>
<% end %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-6"> <!-- shows club information -->
      <p><strong>Name:</strong> <%= @club.name %></p>
      <p><strong>Description:</strong> <%= @club.description %></p>
      <p><strong>Number of Members:</strong> <%= @club.member_number %></p>
      <p><strong>Club Type:</strong> <%= link_to @club.type.name, type_path(@club.type) %></p><br>
      
      <h5><strong>Members:</strong></h5>
      <% if @club.members.any? %>
        <% @club.members.each do |member| %>
          <strong><%= member.position %></strong> - <%= member.name %><br>
        <% end %>
      <% else %>
        <p>No members</p>
      <% end %>

      <%= link_to 'Edit Club', edit_club_path(@club) %> |
      <%= link_to 'Back to Clubs', clubs_path %>
    </div>

    <div class="col-sm-6"> <!-- Allows user to build a new post for this club -->
      <strong>Add a new Post:</strong><br>
        <%= render partial: "posts/newform", locals: {club: @club} %>
    </div>
  </div>
</div>

<div class="posts-container"> <!-- shows posts in this club -->
  <h2><strong>Posts:</strong></h2><br><br>
  <% if @club.posts.empty? %>
    <p>There are no posts yet.</p>
  <% else %>
    <div class="posts">
      <% @club.posts.reverse_each do |post| %>
        <%= render partial: "posts/post", locals: {post: post} %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/clubs/update.js.erb
$('form').hide();
$('div#<%= dom_id(@club) %>').replaceWith('<%= j render partial: "club", locals: {club: @club} %>');

app/views/layouts/_header.html.erb
<nav id="navcontainer">
  <% if !!current_user %>
    <div class="container">
      <div class="row">
        <div class="col-sm-4"><%= link_to "Home", root_path %></div>
        <div class="col-sm-4"><%= link_to "Edit Account", edit_user_registration_path %></div>
        <div class="col-sm-4"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></div>
      </div>
    </div>
  <% else %>
    <div class="container">
      <div class="row">
        <div class="col-sm-3"><%= link_to "Home", root_path %></div>
        <div class="col-sm-3"><%= link_to "Sign up", new_user_registration_path %></div>
        <div class="col-sm-3"><%= link_to "Sign in", new_user_session_path %></div>
        <div class="col-sm-3"><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %></div>
      </div>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClubPosts</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/header' %>
  </header>
    
  <%= yield %>

</body>
</html>

app/views/members/search.html.erb
<h3>Enter the position you would like to search for:</h3>
<%= form_tag "/members/search", method: "get" do %>
  <%= text_field_tag :position, params[:position] %>
  <%= submit_tag("Search") %>
<% end %>

app/views/members/show.html.erb
<div>
  <h1>All of the <%= @position %>'s</h1>
  <% @members.each do |member|%>
    <p><%= member.name %> from <%= link_to member.club.name, club_path(member.club) %></p>
  <% end %>
</div>

app/views/posts/_edit.html.erb
<%= form_for @post, action: posts_path, remote: true, method: 'patch' do |f| %>
  <h6>Title:</h6>
  <%= f.text_field :title,  placeholder: "Add a title." %><br>
  <h6>Content:</h6>
  <%= f.text_area :content, placeholder: "Add some content." %>
  <%= f.submit %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post, remote: true) do |f| %>
  <h6>Title:</h6>
  <%= f.text_field :title,  placeholder: "Add a title." %><br>
  <h6>Content:</h6>
  <%= f.text_area :content, placeholder: "Add some content." %>
  <br>
  <%= f.submit %>
<% end %>

app/views/posts/_newform.html.erb
<%= form_for Post.new, action: posts_path, remote: true, method: 'post' do |f| %>
  
  <h6>Title:</h6>
  <%= f.text_field :title,  placeholder: "Add a title." %><br>
  
  <h6>Content:</h6>
  <%= f.text_area :content, placeholder: "Add some content." %>

  <%= f.hidden_field :club_id, value: @club.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  
  <%= f.submit %>
<% end %>

app/views/posts/_post.html.erb
<%= div_for post do %>
  <div class="post-panel">
    <h5><%= post.title%></h5>

    <div id="content-<%= post.id %>">
      <% if post.content.length > 17 %>
        <%= truncate post.content %>
        <button class="js-more" data-id="<%= post.id %>">More...</button>
      <% else %>
        <%= post.content %>
      <% end %>
    </div>

    <h6>Posted by: <%= post.user.email %></h6>
    <h6><%= post.created_at.strftime("%A, %d %b %Y %l:%M %p") %></h6>
    <%= link_to 'Edit', edit_post_path(post), remote: true %> |
    <%= link_to "delete", post, remote: true, method: "DELETE" %>
    <hr>
  </div>
<% end %>

app/views/posts/create.js.erb
$('.posts').prepend('<%= j render partial: ('post'), locals: {post: @post} %>');

app/views/posts/destroy.js.erb
$('div#<%= dom_id(@post) %>').fadeOut();

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', club_path(@post.club) %>

app/views/posts/edit.js.erb
$('div#<%= dom_id(@post) %>').find('.post-panel').append('<%= j render("form") %>');

app/views/posts/index.html.erb
<h1>Posts:</h1>

<% if !@posts.empty? %>
  <%= render partial: 'newform', :locals => {:post => @post} %>
<% else %>
  <h3>There is nothing to display here</h3>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <p><strong>Content:</strong> <%= @post.content %></p>
  <%= link_to 'Back', clubs_path %>
</div>

app/views/posts/update.js.erb
$('div#<%= dom_id(@post) %>').replaceWith('<%= j render partial: "post", locals: {post: @post} %>');

app/views/types/_type.html.erb
<%= type.name %>

app/views/types/index.html.erb
<div id="message"></div>

<h3>Create a new type of club.</h3>
  <%= form_for @type, remote: true do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
<hr><br>

<h2>Types</h2>

<p><button id="types-btn" class="btn">Show Club Types</button></p>

<div id="types">
</div>

app/views/types/show.html.erb
<h1><%= @type.name %> Clubs</h1>

<% @type.clubs.each do |club| %>
  <h3><%= link_to club.name, club_path(club) %></h3>
  <p><%= club.member_number %> members.</p><br>
<% end %>

app/views/types/show.js.erb
<%= j render @type %>;